name: Continuous Integration and Deployment #name of our cd cd

on: #on means, when it works, in our case it work on push, so when we push to master branch it works
    push:
        branches:
            - master

# We can declare a variables just for readability purposes and clean configuration
env:
    DOTNET_VERSION: '8.0'
    AZURE_WEBAPP_NAME: 'umrah-tour-webapp'

jobs: #so it asks what should happen when we push and it is called jobs
    build: # job is build
        runs-on: ubuntu-latest #where to run - in our case it is ubuntu server
        steps: #after that we specify steps, what steps should happen, we can see steps in here: https://github.com/marketplace?type=actions
            - name: Check out code
              uses: actions/checkout@v4
            
            - name: setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0' # we can use env variables instead of direct values: ${env.DOTNET_VERSION}}
            
            - name: Restore dependencies
              run: dotnet restore
 
            - name: Build app
              run: dotnet build -c Release --no-restore

            - name: Run tests
              run: dotnet test -c Release --no-build

            - name: Publish app
              run: dotnet publish -c Release -o ./out

            - name: Deploy to Azure web apps
              uses: azure/webapps-deploy@v2
              with:
                app-name: umrah-tour-webapp
                publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SECRET }}
                package: ./out



            